### Let's implement a Perceptron

model = Perceptron(dim =4)

X # is data with shape (m,n) m = observations, n=attributes
Y # is labels (m,)
train_X, train_Y, test_X, test_Y

model.fit(train_X, train_Y)

y_hat = model.predict(test_x)

In [3]:
#conda install -c conda-forge scikit-learn -y

Solving environment: done

## Package Plan ##

  environment location: /Users/ronaldadomako/anaconda3

  added / updated specs:
    - scikit-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    joblib-0.14.1              |             py_0         198 KB  conda-forge
    scikit-learn-0.22.2.post1  |   py37h3dc85bc_0         6.3 MB  conda-forge
    scipy-1.4.1                |   py37hce1b9e5_3        18.9 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        25.4 MB

The following NEW packages will be INSTALLED:

  joblib             conda-forge/noarch::joblib-0.14.1-py_0
  scikit-learn       conda-forge/osx-64::scikit-learn-0.22.2.post1-py37h3dc85bc_0
  scipy              conda-forge/osx-64::scipy-1.4.1-py37hce1b9e5_3



scipy-1.4.1          | 18.9 MB   | ##################################### | 100% 
s

In [4]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [5]:
def decision_function(z):
    '''
    if z >= 0:
        return 1
    else:
        return -1
    '''
    return np.where(z >= 0.0,1,-1)

class Perceptron:
    def __init__(self,dim=4, eta =0.1, max_epochs =100):
        self.dim = dim
        #self._w = np.zeros((1,dim))
        self._w = np.random.random((1,dim))
        self.eta = eta
        self.max_epochs = max_epochs
        
    def predict(self, X):
        return decision_function(np.dot(X, self._w.T))
    
    def fit (self, X,Y):
        for epoch in range(self.max_epochs):
            for x,y in zip(X,Y):
                yhat = self.predict(x)
                delta_w = self.eta*(y-yhat)*x
                self._w = self._w + delta_w
        

In [6]:
model = Perceptron()

In [7]:
print(model._w)

[[0.91807347 0.04759559 0.83506753 0.07595078]]


In [8]:
model.predict(np.array([[1,2,3,4]]))


array([[1]])

In [9]:
X = np.array([[1,2,3,4]])

In [10]:
X = np.array([[1,2,3,4],[5,6,7,8]])

In [11]:
model.predict(X)

array([[1],
       [1]])

In [12]:
for ind, row in enumerate(X):
    print(ind,':', row)

0 : [1 2 3 4]
1 : [5 6 7 8]


In [13]:
Y = [[7],[2]]

In [14]:
model.fit(X,Y)

In [15]:
print(model._w)

[[110.91807347 180.04759559 250.83506753 320.07595078]]


In [16]:
help(load_iris)

Help on function load_iris in module sklearn.datasets._base:

load_iris(return_X_y=False)
    Load and return the iris dataset (classification).
    
    The iris dataset is a classic and very easy multi-class classification
    dataset.
    
    =================   ==============
    Classes                          3
    Samples per class               50
    Samples total                  150
    Dimensionality                   4
    Features            real, positive
    =================   ==============
    
    Read more in the :ref:`User Guide <iris_dataset>`.
    
    Parameters
    ----------
    return_X_y : boolean, default=False.
        If True, returns ``(data, target)`` instead of a Bunch object. See
        below for more information about the `data` and `target` object.
    
        .. versionadded:: 0.18
    
    Returns
    -------
    data : Bunch
        Dictionary-like object, the interesting attributes are:
        'data', the data to learn, 'target', the class

In [17]:
X,Y = predict

NameError: name 'predict' is not defined