### Let's implement a Perceptron

model = Perceptron(dim =4)

X # is data with shape (m,n) m = observations, n=attributes
Y # is labels (m,)
train_X, train_Y, test_X, test_Y

model.fit(train_X, train_Y)

y_hat = model.predict(test_x)

In [129]:
conda install -c conda-forge scikit-learn -y

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.0
  latest version: 4.8.2

Please update conda by running

    $ conda update -n base conda


Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.0
  latest version: 4.8.2

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /anaconda3/envs/ipk3

  added / updated specs:
    - scikit-learn


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    joblib-0.14.1              |             py_0         198 KB  conda-forge
    scikit-learn-0.22          |   py38h3dc85bc_1         6.4 MB  conda-forge
    ------------------------------------------------------------
                                           Tota

In [130]:
import numpy as np

from sklearn.dataset import load_iris
from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'sklearn.dataset'

In [110]:
def decision_function(z):
    '''
    if z >= 0:
        return 1
    else:
        return -1
    '''
    return np.where(z >= 0.0,1,-1)

class Perceptron:
    def __init__(self,dim=4, eta =0.1, max_epochs =100):
        self.dim = dim
        #self._w = np.zeros((1,dim))
        self._w = np.random.random((1,dim))
        self.eta = eta
        self.max_epochs = max_epochs
        
    def predict(self, X):
        return decision_function(np.dot(X, self._w.T))
    
    def fit (self, X,Y):
        for epoch in range(self.max_epochs):
            for x,y in zip(X,Y):
                yhat = self.predict(x)
                delta_w = self.eta*(y-yhat)*x
                self._w = self._w + delta_w
        

In [111]:
model = Perceptron()

In [112]:
print(model._w)

[[0.74744126 0.27337367 0.58708099 0.95981802]]


In [113]:
model.predict(np.array([[1,2,3,4]]))


array([[1]])

In [114]:
X = np.array([[1,2,3,4]])

In [115]:
X = np.array([[1,2,3,4],[5,6,7,8]])

In [116]:
model.predict(X)

array([[1],
       [1]])

In [117]:
for ind, row in enumerate(X):
    print(ind,':', row)

0 : [1 2 3 4]
1 : [5 6 7 8]


In [118]:
Y = [[7],[2]]

In [119]:
model.fit(X,Y)

In [120]:
print(model._w)

[[110.74744126 180.27337367 250.58708099 320.95981802]]


In [126]:
help(load_iris)

NameError: name 'load_iris' is not defined

In [ ]:
X,Y = predict